name: 'action-demo'
description: 'an action demo.'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
jobs:
  job0:
    name: job0
    runs-on: ubuntu-latest
    steps:
    - name: echo repository name
        shell: bash 
        run: |
          echo ${{ github.repository }}
