name: "action-demo"
description: "an action demo."
inputs:
  repository:
    description: "Repository name with owner. For example, actions/checkout"
    default: ${{ github.repository }}
    
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo hello
        echo ${{ github.repository }}
        echo ${{ github.action_repository }}
        echo ${{ github.action_ref }}
        
