name: "action-demo"
description: "an action demo."
inputs:
  repository:
    description: "Repository name with owner. For example, actions/checkout"
    default: ${{ github.repository }}
  list:
    
runs:
  using: composite
  steps:
    - name: shim-path
      shell: bash
      run: |
        echo ${{ github.repository }}
        echo ${{ github.ref }}
        echo "GH_ACTION_REPOSITORY=$GH_ACTION_REPOSITORY"
        echo "GH_ACTION_REF=$GH_ACTION_REF"
      env:
        GH_ACTION_REPOSITORY: ${{ github.action_repository || github.repository }}
        GH_ACTION_REF: ${{ github.action_ref || github.ref_name }}
    - shell: bash
      run: |
        echo hello
        echo ${{ inputs.list }}
