name: 'action-demo'
description: 'an action demo.'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
jobs:
  job0:
    name: job0
    steps:
    - name: echo repository name
        run: echo ${{ github.repository }}
