name: "action-demo"
description: "an action demo."
inputs:
  repository:
    description: "Repository name with owner. For example, actions/checkout"
    default: ${{ github.repository }}
    
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo hello
        echo ${{ github.repository }}
    - uses: RT-Thread/pkgs-test/.github/workflows/pkgs-action.yml@main
