name: test

on:
  workflow_call:
    inputs:
      test:
        description: "test"
        default: "test"
        required: false
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "${{ github.workflow_ref }}"
          echo ${{ github.repository }}
          echo ${{ github.ref }}
          echo "GH_ACTION_REPOSITORY=$GH_ACTION_REPOSITORY"
          echo "GH_ACTION_REF=$GH_ACTION_REF"
        env:
          GH_ACTION_REPOSITORY: ${{ github.action_repository || github.repository }}
          GH_ACTION_REF: ${{ github.action_ref || github.ref_name }}
